// <auto-generated />
using System;
using Licitatii;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licitatii.Migrations
{
    [DbContext(typeof(ContextLicitatii))]
    partial class ContextLicitatiiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CandidatLicitatie", b =>
                {
                    b.Property<int>("CandidatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LicitatiiLicitatieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidatId", "LicitatiiLicitatieId");

                    b.HasIndex("LicitatiiLicitatieId");

                    b.ToTable("CandidatLicitatie");
                });

            modelBuilder.Entity("Licitatii.Models.Candidat", b =>
                {
                    b.Property<int>("CandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Varsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidatId");

                    b.ToTable("Candidati");
                });

            modelBuilder.Entity("Licitatii.Models.Licitatie", b =>
                {
                    b.Property<int>("LicitatieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsteFinalizata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoareFinala")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoareStart")
                        .HasColumnType("TEXT");

                    b.HasKey("LicitatieId");

                    b.ToTable("Licitatii");
                });

            modelBuilder.Entity("Licitatii.Models.Oferta", b =>
                {
                    b.Property<int>("OfertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOferta")
                        .HasColumnType("TEXT");

                    b.Property<int>("LicitatieId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SumaOferita")
                        .HasColumnType("TEXT");

                    b.HasKey("OfertaId");

                    b.HasIndex("CandidatId");

                    b.HasIndex("LicitatieId");

                    b.ToTable("Oferte");
                });

            modelBuilder.Entity("CandidatLicitatie", b =>
                {
                    b.HasOne("Licitatii.Models.Candidat", null)
                        .WithMany()
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licitatii.Models.Licitatie", null)
                        .WithMany()
                        .HasForeignKey("LicitatiiLicitatieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Licitatii.Models.Oferta", b =>
                {
                    b.HasOne("Licitatii.Models.Candidat", "Candidat")
                        .WithMany("Oferte")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licitatii.Models.Licitatie", "Licitatie")
                        .WithMany("Oferte")
                        .HasForeignKey("LicitatieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Licitatie");
                });

            modelBuilder.Entity("Licitatii.Models.Candidat", b =>
                {
                    b.Navigation("Oferte");
                });

            modelBuilder.Entity("Licitatii.Models.Licitatie", b =>
                {
                    b.Navigation("Oferte");
                });
#pragma warning restore 612, 618
        }
    }
}
